### ISSUE TITLE
Error building the extension on Bupr Enterprise

### ISSUE THREAD

**Issue by ivanov21** [UthmanPortSwigger/add-custom-headers#2]
Get this same error with burp enterprise
<img width="895" alt="custom header error" src="https://user-images.githubusercontent.com/38586468/156791347-07cca2dd-60c1-44f4-a58f-29a034737892.png">

**Comment by UthmanPortSwigger** [comment]
Hi, 

That looks like a PowerShell syntax issue. 

Try this: 

`./gradlew "-Dorg.gradle.java.home=C:\Program Files\burpsuite_enterprise\jres\11.0.13.8.1" fatJar`

For CMD, you can use `gradlew -Dorg.gradle.java.home="C:\Program Files\burpsuite_enterprise\jres\11.0.13.8.1" fatJar` 

Hope this helps! 😊

**Comment by ivanov21** [comment]
It works,
Thanks
