### ISSUE TITLE
Enteprise build issue

### ISSUE THREAD

**Issue by ironfistotkp** [UthmanPortSwigger/add-custom-headers#3]
I am using mac machine to build the extension. To test with burp community its fine on macbook. But to build for enterprise(hosted on windoes) i passed correct jres directory in mac. Its not building the extension getting this error ```Value 'C:\Program' given for org.gradle.java.home Gradle property is invalid (Java home supplied is invalid)```

Does that mean i need to build the extension in same enterprise machine ??

**Comment by Hannah-PortSwigger** [comment]
You will need to provide a valid filepath to your JRE.

The instructions given (in the "Notes for Enterprise users" section) assume that you are running the build command on a machine with Enterprise installed.
